# This is a basic workflow to help you get started with Actions

name: continuous integration pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK 16
        uses: actions/setup-java@v2.3.0
        with:
          java-version: '16'
          distribution: 'adopt'
          cache: maven
      - name: Build with maven
        run: mvn -B verify --file pom.xml
