
name: release project

on:
  push:
    branches: [ 'release-**' ]
  pull_request:
    branches: [ 'release-**' ]
    
  workflow_dispatch:

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
        cache: maven
    
    - name: Run java checkstyle
      uses: nikitasavinov/checkstyle-action@0.4.0
   
    - name: Build with Maven
      run: mvn package
